### ISSUE TITLE
Issues with `remove_models_except` implementation

### ISSUE THREAD

**Issue by douweschulte** [douweschulte/pdbtbx#104]
I made a unit test for `remove_models_except` to test out the new features and it shows some problems with the implementation. When I remove all except `&[5, 1, 3]` the resulting pdb contains models `[5, 0, 1]`. I added the unit test in the branch `remove_except_issue` for ease of testing, alongside a very simple testing pdb. @OWissett could you look into this?

**Comment by OWissett** [comment]
Yes, I will fix this in the morning! Thanks for the catch!

**Comment by OWissett** [comment]
This will be because of index shifting, I thought I accounted for this, but clearly not... lol
