### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by douweschulte** [douweschulte/pdbtbx#60]
Having examples which show how a library works and how people can use it for their own projects is a very important part of documentation. I would like to invite anyone to add more examples to the documentation, especially if you have used this library for one of your own projects.

A great place to initially add an example would be to the integration tests `/tests/` folder in this way it will automatically be run every time the code is updated so it is guaranteed to keep running. As soon as an example is added we can discuss the best place to put it like the readme or docs or something else.

**Comment by DocKDE** [comment]
I was thinking about taking a couple of the functions I wrote and adding them as tests. However, they make use of the `rstar` feature that is disabled by default. Do you know how to write a test using a disabled-by-default feature? Wasn't able to find much on the subject.

**Comment by nonnominandus** [comment]
I made a couple tests using `rstar` already, you could take a look at them to see how it can be done. The tests are [`spatial_lookup`](https://github.com/nonnominandus/pdbtbx/blob/master/src/structs/pdb.rs#L948) and [`spatial_lookup_with_hierarchy`](https://github.com/nonnominandus/pdbtbx/blob/master/src/structs/pdb.rs#L993). In general it boils down to not including the test if a certain compiler flag is not available (if a feature is not active). This can be done using the conditional compilation compiler directives `#[cfg(...)]`.

```rust
    #[test]
    #[cfg(feature = "rstar")]
    fn spatial_lookup_with_hierarchy() {
        let mut model = Model::new(0);
        // .. add atoms
        let mut pdb = PDB::new();
        pdb.add_model(model);
        let tree = pdb.create_atom_with_hierarchy_rtree();
        assert_eq!(tree.size(), 3);
        /.. assertions
    }
```

Good luck and if you find that one of your tests would also be beneficial as an example in the documentation feel free to add it there as well. Adding an example of a diabled-by-defaulft feature is a bit more finicky, see [this piece](https://github.com/nonnominandus/pdbtbx/blob/master/src/lib.rs#L127) for how I figured it out. Note that `r##"` is a raw string literal see [this](https://doc.rust-lang.org/rust-by-example/std/str.html).
