### ISSUE TITLE
Allow for the use of compressed files

### ISSUE THREAD

**Issue by douweschulte** [douweschulte/pdbtbx#99]
I found (this great fork)[https://github.com/ykgkhakase/pdbtbx]. If @ykgkhakase is open to it I would happily accept a pull request.

In the best case pdbtbx would support both zipped pdb (`.pdb.gz`) and mmCif (`.cif.gz`) files, both for opening and writing. Also a setup with this behaviour behind a (default on) feature flag would have my preference.

**Comment by OWissett** [comment]
Not seen any activity on this. I might just try and implement this myself. I have something similar to this already. Shouldn't be too hard

**Comment by OWissett** [comment]
Can you assign this ticket to me?

**Comment by douweschulte** [comment]
Perfect! I assigned you to this.

**Comment by OWissett** [comment]
PR now open
